import { Link } from 'react-router-dom';
import { Button } from '../components/ui/button';
import { Separator } from '../components/ui/separator';
import { ArrowLeft } from 'lucide-react';

export default function Terms() {
  return (
    <div className="max-w-3xl mx-auto px-4 sm:px-6 lg:px-8 py-12 space-y-8" data-testid="terms-page">
      <div className="flex items-center gap-3">
        <Link to="/"><Button variant="ghost" size="icon" data-testid="back-btn"><ArrowLeft className="w-4 h-4" /></Button></Link>
        <div>
          <h1 className="text-3xl font-bold tracking-tight font-heading">Terms of Service</h1>
          <p className="text-sm text-muted-foreground">Last updated: March 10, 2026</p>
        </div>
      </div>

      <div className="space-y-6">
        <section className="space-y-3">
          <h2 className="text-lg font-semibold font-heading">1. Acceptance of Terms</h2>
          <p className="text-sm text-muted-foreground leading-relaxed">By accessing or using InterviewMaster, you agree to be bound by these Terms of Service. If you do not agree to these terms, please do not use the platform.</p>
        </section>
        <Separator />
        <section className="space-y-3">
          <h2 className="text-lg font-semibold font-heading">2. Use of the Platform</h2>
          <p className="text-sm text-muted-foreground leading-relaxed">InterviewMaster is designed for personal interview preparation purposes. You agree to use the platform lawfully and not to misuse any features, including AI-generated content, recordings, or feedback systems.</p>
        </section>
        <Separator />
        <section className="space-y-3">
          <h2 className="text-lg font-semibold font-heading">3. User Accounts</h2>
          <p className="text-sm text-muted-foreground leading-relaxed">You are responsible for maintaining the security of your account credentials. You must not share your account with others. We reserve the right to suspend accounts that violate these terms.</p>
        </section>
        <Separator />
        <section className="space-y-3">
          <h2 className="text-lg font-semibold font-heading">4. Content Ownership</h2>
          <p className="text-sm text-muted-foreground leading-relaxed">Your recordings, transcripts, and uploaded resumes remain your property. By using the platform, you grant us a limited license to process this content for the purpose of providing our services (question generation, AI feedback, etc.).</p>
        </section>
        <Separator />
        <section className="space-y-3">
          <h2 className="text-lg font-semibold font-heading">5. AI-Generated Content</h2>
          <p className="text-sm text-muted-foreground leading-relaxed">Interview questions and feedback are generated by AI models. While we strive for accuracy, AI-generated content may not always be perfect. It should be used as a practice tool, not as definitive career advice.</p>
        </section>
        <Separator />
        <section className="space-y-3">
          <h2 className="text-lg font-semibold font-heading">6. Limitation of Liability</h2>
          <p className="text-sm text-muted-foreground leading-relaxed">InterviewMaster is provided "as is" without warranties of any kind. We are not liable for any outcomes resulting from the use of our platform, including interview performance or employment decisions.</p>
        </section>
        <Separator />
        <section className="space-y-3">
          <h2 className="text-lg font-semibold font-heading">7. Changes to Terms</h2>
          <p className="text-sm text-muted-foreground leading-relaxed">We may update these terms from time to time. Continued use of the platform after changes constitutes acceptance of the new terms. We will notify users of significant changes via email or in-app notification.</p>
        </section>
        <Separator />
        <section className="space-y-3">
          <h2 className="text-lg font-semibold font-heading">8. Contact</h2>
          <p className="text-sm text-muted-foreground leading-relaxed">For questions about these Terms, contact us at <span className="text-primary">arghyanilryzen@gmail.com</span>.</p>
        </section>
      </div>
    </div>
  );
}
